# Generated by Django 3.1.7 on 2022-01-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='latitide',
            new_name='latitude',
        ),
    ]
