# Generated by Django 3.1.7 on 2022-01-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_point_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.TextField(default='Екатеринбург'),
            preserve_default=False,
        ),
    ]
