# Generated by Django 3.1.7 on 2022-02-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20220117_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.CharField(default='asdsadasd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='point_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='map.point'),
        ),
    ]
